## Traefik dynamic configuration - homelab services routed via Tailscale

http:
  routers:
    portainer:
      rule: "Host(`portainer.harmonops.com`)"
      entryPoints:
        - "https"
      middlewares:
        - "authelia@docker"
      service: "portainer"

    pihole:
      rule: "Host(`pihole.harmonops.com`)"
      entryPoints:
        - "https"
      middlewares:
        - "authelia@docker"
      service: "pihole"

  services:
    portainer:
      loadBalancer:
        servers:
          - url: "http://100.111.111.101:9000"

    pihole:
      loadBalancer:
        servers:
          - url: "http://100.111.111.101:80"
